const characterData = {
  wizard: {
    name: "Wizard",
    avatar: "wizard.png",
    health: 70,
    attack: 1,
    diceCount: 3,
    currentDiceScore: [],
    emoji: "🧙🏽‍♂️",
    specialAttack: "Fireball",
  },
  knight: {
    name: "Knight",
    avatar: "knight.png",
    health: 80,
    attack: 2,
    diceCount: 2,
    currentDiceScore: [],
    emoji: "🛡",
    specialAttack: "Shield Bash",
  },
  elf: {
    name: "Elf",
    avatar: "elf.png",
    health: 75,
    attack: 3,
    diceCount: 2,
    currentDiceScore: [],
    emoji: "🧝🏼‍♂️",
    specialAttack: "Arrow Shot",
  },
  orc: {
    name: "Orc",
    avatar: "orc.png",
    health: 30,
    attack: 3,
    diceCount: 1,
    currentDiceScore: [],
    emoji: "💀",
  },
  demon: {
    name: "Demon",
    avatar: "demon.png",
    health: 25,
    attack: 2,
    diceCount: 2,
    currentDiceScore: [],
    emoji: "💀",
  },
  goblin: {
    name: "Goblin",
    avatar: "goblin.png",
    health: 20,
    attack: 1,
    diceCount: 3,
    currentDiceScore: [],
    emoji: "💀",
  },
};

export default characterData;
